version: '3'
networks:
  app:
volumes:
  mongo_db: {}
services:
  db:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_db:/data/db
  api:
    container_name: node
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URL: 'mongodb+srv://Vteams:ElectricTeams@cluster0.6swmyvj.mongodb.net/?retryWrites=true&w=majority'
      JWTSECRET: "C1jLZUkOBF4MZwy"
      GITHUBCLIENTID: "6cf1f637f3f432873249"
      GITHUBCLIENTSECRET: "d00f008de7fd63961fe60c077944d652054c340d"
    networks:
      app:
  vteams-frontend:
    container_name: vue
    build: ./../vteams-frontend
    ports:
      - '8080:8080'
    networks:
      app: