name: Docker Flow Backend

on:
  push:
    branches: [dev]
    
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker build image
      run: docker build -t kristinakalinchuk/vteams-backend .
    - name: docker push image
      run: docker push kristinakalinchuk/vteams-backend
