name: Docker Flow Backend

on:
  push:
    branches: [dev]
    
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: dockerhub login
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
      run: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD
    - name: docker build image
      run: docker build -t kristinakalinchuk/vteams-backend .
    - name: docker push image
      run: docker push kristinakalinchuk/vteams-backend
